const CREATED_STATUS_CODE = 201;
const VALIDATION_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const ACCESS_DENIED_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const ALREADY_EXIST_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

const URL_REGEX = /https?:\/\/(www\.)?[\d\S]+$/i;

module.exports = {
  CREATED_STATUS_CODE,
  VALIDATION_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  ACCESS_DENIED_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  ALREADY_EXIST_CODE,
  DEFAULT_ERROR_CODE,
  URL_REGEX,
};
